name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-templates:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        rust: [ "1.93.0", "stable" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: wasm32-wasip2, wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-leptos
        run: |
          cargo binstall -y cargo-leptos@0.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "v4.0.0"

      - name: Install Templates
        run: |
          spin templates install --dir . --upgrade

      - name: Test Scaffold - leptos-wasmtime
        run: |
          spin new test-wasmtime-app -t leptos-wasmtime
          cd test-wasmtime-app
          cargo check
          cargo check --features ssr
          cargo check --features hydrate

      - name: Test Scaffold - leptos-spin
        run: |
          spin new test-spin-app -t leptos-spin
          cd test-spin-app
          cargo check
          cargo check --features ssr
          cargo check --features hydrate
